import { Award, BarChart3, TrendingDown, TrendingUp } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header";
import { EmptyState } from "@/components/shared/empty-state";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { SubjectAverageBarChart } from "@/charts/subject-average-bar-chart";
import { DepartmentPerformanceBarChart } from "@/charts/department-performance-bar-chart";
import { GradeDistributionPieChart } from "@/charts/grade-distribution-pie-chart";
import { PassFailDonutChart } from "@/charts/pass-fail-donut-chart";
import {
  getDashboardMetrics,
  getDepartmentPerformance,
  getGradeDistribution,
  getPassFailRatio,
  getStudentRankings,
  getSubjectFailureAnalysis,
  getSubjectPerformance,
  getWeakStudents,
} from "@/services/analyticsService";

export const dynamic = "force-dynamic";

export default async function AnalyticsPage() {
  const [metrics, rankings, subjectPerformance, departmentPerformance, gradeDistribution, weakStudents, failures, passFailRatio] =
    await Promise.all([
      getDashboardMetrics(),
      getStudentRankings(),
      getSubjectPerformance(),
      getDepartmentPerformance(),
      getGradeDistribution(),
      getWeakStudents(),
      getSubjectFailureAnalysis(),
      getPassFailRatio(),
    ]);

  if (metrics.totalMarksEntries === 0) {
    return (
      <div>
        <PageHeader title="Analytics" description="The heart of InsightEDU, powered entirely by MongoDB Aggregation Pipelines." />
        <EmptyState icon={BarChart3} title="Add Data To Generate Insights" />
      </div>
    );
  }

  const topStudents = rankings.slice(0, 10);
  const totalGrades = gradeDistribution.reduce((sum, item) => sum + item.count, 0);

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Analytics"
        description="The heart of InsightEDU — every metric below is generated by a MongoDB Aggregation Pipeline."
      />

      {/* Section 1 + 2: Student Rankings & Top 10 */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <Award className="size-4 text-primary" />
            Top 10 Students
          </CardTitle>
          <CardDescription>Ranked by average score across all subjects.</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-16">Rank</TableHead>
                <TableHead>Student</TableHead>
                <TableHead>Department</TableHead>
                <TableHead className="text-right">Average Score</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {topStudents.map((student) => (
                <TableRow key={student.studentId}>
                  <TableCell>
                    <Badge variant={student.rank <= 3 ? "default" : "secondary"}>#{student.rank}</Badge>
                  </TableCell>
                  <TableCell className="font-medium">
                    {student.name}
                    <span className="block text-xs text-muted-foreground">{student.studentDisplayId}</span>
                  </TableCell>
                  <TableCell>{student.department}</TableCell>
                  <TableCell className="text-right font-semibold">{student.averageScore}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Full Student Rankings</CardTitle>
          <CardDescription>{rankings.length} students ranked by average score.</CardDescription>
        </CardHeader>
        <CardContent className="max-h-96 overflow-y-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-16">Rank</TableHead>
                <TableHead>Student</TableHead>
                <TableHead className="text-right">Average Score</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {rankings.map((student) => (
                <TableRow key={student.studentId}>
                  <TableCell className="text-muted-foreground">#{student.rank}</TableCell>
                  <TableCell>{student.name}</TableCell>
                  <TableCell className="text-right">{student.averageScore}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Section 3: Subject Performance */}
      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Subject Performance</CardTitle>
            <CardDescription>Average score by subject.</CardDescription>
          </CardHeader>
          <CardContent>
            <SubjectAverageBarChart data={subjectPerformance} />
          </CardContent>
        </Card>

        {/* Section 6: Department Performance */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Department Performance</CardTitle>
            <CardDescription>Average marks by department.</CardDescription>
          </CardHeader>
          <CardContent>
            <DepartmentPerformanceBarChart data={departmentPerformance} />
          </CardContent>
        </Card>
      </div>

      {/* Section 5: Grade Distribution */}
      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Grade Distribution</CardTitle>
            <CardDescription>O: 90+ · A+: 80-89 · A: 70-79 · B: 60-69 · C: 50-59 · F: Below 50</CardDescription>
          </CardHeader>
          <CardContent>
            <GradeDistributionPieChart data={gradeDistribution} />
          </CardContent>
        </Card>

        {/* Section 8: Pass Percentage */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base flex items-center gap-2">
              <TrendingUp className="size-4 text-success" />
              Pass Percentage
            </CardTitle>
            <CardDescription>Passing marks threshold: 40</CardDescription>
          </CardHeader>
          <CardContent>
            <PassFailDonutChart data={passFailRatio} />
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Grade Breakdown</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Grade</TableHead>
                <TableHead>Count</TableHead>
                <TableHead className="text-right">Share</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {gradeDistribution.map((bucket) => (
                <TableRow key={bucket.grade}>
                  <TableCell>
                    <Badge variant="secondary">{bucket.grade}</Badge>
                  </TableCell>
                  <TableCell>{bucket.count}</TableCell>
                  <TableCell className="text-right">
                    {totalGrades > 0 ? `${Math.round((bucket.count / totalGrades) * 1000) / 10}%` : "0%"}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Section 4: Weak Students */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <TrendingDown className="size-4 text-destructive" />
            Weak Students
          </CardTitle>
          <CardDescription>Students with an average score below 50.</CardDescription>
        </CardHeader>
        <CardContent>
          {weakStudents.length === 0 ? (
            <p className="text-sm text-muted-foreground py-6 text-center">
              No weak students — everyone is averaging 50 or above.
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Student</TableHead>
                  <TableHead>Department</TableHead>
                  <TableHead className="text-right">Average Score</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {weakStudents.map((student) => (
                  <TableRow key={student.studentId}>
                    <TableCell className="font-medium">
                      {student.name}
                      <span className="block text-xs text-muted-foreground">{student.studentDisplayId}</span>
                    </TableCell>
                    <TableCell>{student.department}</TableCell>
                    <TableCell className="text-right">
                      <Badge variant="destructive">{student.averageScore}</Badge>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Section 7: Subject Failure Analysis */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Subject Failure Analysis</CardTitle>
          <CardDescription>Subjects with the highest failure rates.</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Subject</TableHead>
                <TableHead>Total Entries</TableHead>
                <TableHead>Failed</TableHead>
                <TableHead className="text-right">Failure Rate</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {failures.map((subject) => (
                <TableRow key={subject.subjectId}>
                  <TableCell className="font-medium">
                    {subject.subjectName}
                    <span className="block text-xs text-muted-foreground">{subject.subjectCode}</span>
                  </TableCell>
                  <TableCell>{subject.totalEntries}</TableCell>
                  <TableCell>{subject.failedCount}</TableCell>
                  <TableCell className="text-right">
                    <Badge variant={subject.failureRate >= 30 ? "destructive" : "secondary"}>
                      {subject.failureRate}%
                    </Badge>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
